spring.application.name=legacy
server.port=9999
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=postgres
spring.datasource.password=ttGssaw@21
spring.jpa.hibernate.ddl-auto=update